--This file contains the constant values needed for the library to work
LibSets = LibSets or {}
local lib = LibSets

-- lookup this "max itemId scanned" for the current patch with the following script:
-- /script local maxId=147664 for itemId=maxId,250000 do local itemType = GetItemLinkItemType('|H1:item:'..tostring(itemId)..':30:1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:10000:0|h|h') if itemType>0 then maxId=itemId end end d(maxId)
--lib.lastSetsPreloadedMaxItemId          = 152255 -- last checked: 2019-06-19, API 1000027
--The last checked API version for the setsData in file LibSets_Data.lua, see "local setItemIdsPreloaded = { ..."
-->Update here after a new scan of the maximum itemId was done (see above) AND the set item's itemIds were updated in file
-->LibSets_Data.lua, table setItemIdsPreloaded -> See description in this file above the table (data from WishList addon e.g.)
lib.lastSetsPreloadedCheckAPIVersion    = 100027 --Elsweyr
------------------------------------------------------------------------------------------------------------------------
--The supported languages of this library
lib.supportedLanguages = {
    ["de"]  = true,
    ["en"]  = true,
    ["fr"]  = true,
    ["jp"]  = true,
    ["ru"]  = true,
}
------------------------------------------------------------------------------------------------------------------------
--Number of currently available set bonus for a monster set piece (2: head, shoulder)
lib.countMonsterSetBonus = 2
------------------------------------------------------------------------------------------------------------------------
--DLC & Chapter ID constants (for LibSets)
DLC_BASE_GAME               = 0
DLC_IMPERIAL_CITY           = 1
DLC_ORSINIUM                = 2
DLC_THIEVES_GUILD           = 3
DLC_DARK_BROTHERHOOD        = 4
DLC_SHADOWS_OF_THE_HIST     = 5
DLC_MORROWIND               = 6
DLC_HORNS_OF_THE_REACH      = 7
DLC_CLOCKWORK_CITY          = 8
DLC_DRAGON_BONES            = 9
DLC_SUMMERSET               = 10
DLC_WOLFHUNTER              = 11
DLC_MURKMIRE                = 12
DLC_WRATHSTONE              = 13
DLC_ELSWEYR                 = 14
--Internal achievement example ids of the ESO DLCs and chapters (first achievementId found from each DLC category)
lib.dlcAndChapterAchievementIds = {
    --Imperial city
    [DLC_IMPERIAL_CITY] = 1267,
    --Orsinium
    [DLC_ORSINIUM] = 1393,
    --Thieves Guild
    [DLC_THIEVES_GUILD] = 1413,
    --Dark Brotherhood
    [DLC_DARK_BROTHERHOOD] = 1421,
    --Shadows of the Hist
    [DLC_SHADOWS_OF_THE_HIST] = 1520,
    --Morrowind
    [DLC_MORROWIND] = 1843,
    --Horns of the Reach
    [DLC_HORNS_OF_THE_REACH] = 1940,
    --Clockwork City
    [DLC_CLOCKWORK_CITY] = 2048,
    --Dragon Bones
    [DLC_DRAGON_BONES] = 2104,
    --Summerset
    [DLC_SUMMERSET] = 1845,
    --Wolfhunter
    [DLC_WOLFHUNTER] = 2157,
    --Murkmire
    [DLC_MURKMIRE] = 2340,
    --Wrathstone
    [DLC_WRATHSTONE] = 2265,
    --Elsweyr
    [DLC_ELSWEYR] = 2463,
}
--Internal achievement example ids of the ESO DLCs and chapters
local dlcAndChapterAchievementIds = lib.dlcAndChapterAchievementIds
--For each entry in the list of example achievements above get the name of it's parent category (DLC, chapter)
lib.DLCData = {}
local DLCandCHAPTERdata = lib.DLCData
for dlcId, dlcAchievementId in ipairs(dlcAndChapterAchievementIds) do
    if dlcId and dlcAchievementId and dlcAchievementId > 0 then
        DLCandCHAPTERdata[dlcId] = ZO_CachedStrFormat("<<C:1>>", GetAchievementCategoryInfo(GetCategoryInfoFromAchievementId(dlcAchievementId)))
    end
end
------------------------------------------------------------------------------------------------------------------------
--The undaunted chests
local undauntedChestIds = {
    ["de"] = {
        [1] = "Glirion der Rotbart",
        [2] = "Maj al-Ragath",
        [3] = "Urgarlag Häuptlingsfluch",
    },
    ["en"] = {
        [1] = "Glirion the Redbeard",
        [2] = "Maj al-Ragath",
        [3] = "Urgarlag Chief-bane",
    },
    ["fr"] = {
        [1] = "Glirion Barbe-Rousse",
        [2] = "Maj al-Ragath",
        [3] = "Urgalarg l'Èmasculatrice",
    },
}
lib.undauntedChestIds = undauntedChestIds
------------------------------------------------------------------------------------------------------------------------
--[[
--These itemSubTypes are used for item quality and item level definition inside itemLinks
local NO_CHAMPION_POINTS = 1
local CHAMPION_POINTS_10 = 51
local CHAMPION_POINTS_20 = 52
local CHAMPION_POINTS_30 = 53
local CHAMPION_POINTS_40 = 54
local CHAMPION_POINTS_50 = 55
local CHAMPION_POINTS_60 = 56
local CHAMPION_POINTS_70 = 57
local CHAMPION_POINTS_80 = 58
local CHAMPION_POINTS_90 = 59
local CHAMPION_POINTS_100 = 60
local CHAMPION_POINTS_110 = 61
local CHAMPION_POINTS_120 = 62
local CHAMPION_POINTS_130 = 63
local CHAMPION_POINTS_140 = 64
local CHAMPION_POINTS_150 = 65
local CHAMPION_POINTS_160 = 66
local CHAMPION_POINTS_170 = 67
local CHAMPION_POINTS_180 = 68
lib.itemSubType =
{
    [0]={level=NO_CHAMPION_POINTS,quality=ITEM_QUALITY_NORMAL},
    [1]={level=NO_CHAMPION_POINTS,quality=ITEM_QUALITY_TRASH},
    [2]={level=NO_CHAMPION_POINTS,quality=ITEM_QUALITY_NORMAL},
    [3]={level=NO_CHAMPION_POINTS,quality=ITEM_QUALITY_MAGIC},
    [4]={level=NO_CHAMPION_POINTS,quality=ITEM_QUALITY_ARCANE},
    [5]={level=NO_CHAMPION_POINTS,quality=ITEM_QUALITY_ARTIFACT},
    [6]={level=NO_CHAMPION_POINTS,quality=ITEM_QUALITY_LEGENDARY},
    [7]={level=NO_CHAMPION_POINTS,quality=ITEM_QUALITY_ARCANE},
    [8]={level=NO_CHAMPION_POINTS,quality=ITEM_QUALITY_ARTIFACT},
    [9]={level=NO_CHAMPION_POINTS,quality=ITEM_QUALITY_MAGIC},
    [10]={level=NO_CHAMPION_POINTS,quality=ITEM_QUALITY_MAGIC},
    [11]={level=NO_CHAMPION_POINTS,quality=ITEM_QUALITY_ARCANE},
    [12]={level=NO_CHAMPION_POINTS,quality=ITEM_QUALITY_LEGENDARY},
    [13]={level=NO_CHAMPION_POINTS,quality=ITEM_QUALITY_LEGENDARY},
    [14]={level=NO_CHAMPION_POINTS,quality=ITEM_QUALITY_LEGENDARY},
    [15]={level=NO_CHAMPION_POINTS,quality=ITEM_QUALITY_LEGENDARY},
    [16]={level=NO_CHAMPION_POINTS,quality=ITEM_QUALITY_LEGENDARY},
    [17]={level=NO_CHAMPION_POINTS,quality=ITEM_QUALITY_LEGENDARY},
    [18]={level=NO_CHAMPION_POINTS,quality=ITEM_QUALITY_MAGIC},
    [19]={level=NO_CHAMPION_POINTS,quality=ITEM_QUALITY_MAGIC},
    [20]={level=NO_CHAMPION_POINTS,quality=ITEM_QUALITY_NORMAL},
    [21]={level=NO_CHAMPION_POINTS,quality=ITEM_QUALITY_MAGIC},
    [22]={level=NO_CHAMPION_POINTS,quality=ITEM_QUALITY_ARCANE},
    [23]={level=NO_CHAMPION_POINTS,quality=ITEM_QUALITY_ARTIFACT},
    [24]={level=NO_CHAMPION_POINTS,quality=ITEM_QUALITY_LEGENDARY},
    [25]={level=NO_CHAMPION_POINTS,quality=ITEM_QUALITY_NORMAL},
    [26]={level=NO_CHAMPION_POINTS,quality=ITEM_QUALITY_MAGIC},
    [27]={level=NO_CHAMPION_POINTS,quality=ITEM_QUALITY_ARCANE},
    [28]={level=NO_CHAMPION_POINTS,quality=ITEM_QUALITY_ARTIFACT},
    [29]={level=NO_CHAMPION_POINTS,quality=ITEM_QUALITY_LEGENDARY},
    [30]={level=NO_CHAMPION_POINTS,quality=ITEM_QUALITY_NORMAL},
    [31]={level=NO_CHAMPION_POINTS,quality=ITEM_QUALITY_MAGIC},
    [32]={level=NO_CHAMPION_POINTS,quality=ITEM_QUALITY_ARCANE},
    [33]={level=NO_CHAMPION_POINTS,quality=ITEM_QUALITY_ARTIFACT},
    [34]={level=NO_CHAMPION_POINTS,quality=ITEM_QUALITY_LEGENDARY},
    [35]={level=NO_CHAMPION_POINTS,quality=ITEM_QUALITY_NORMAL},
    [36]={level=NO_CHAMPION_POINTS,quality=ITEM_QUALITY_NORMAL},
    [37]={level=NO_CHAMPION_POINTS,quality=ITEM_QUALITY_NORMAL},
    [38]={level=NO_CHAMPION_POINTS,quality=ITEM_QUALITY_NORMAL},
    [39]={level=CHAMPION_POINTS_10,quality=ITEM_QUALITY_MAGIC},
    [40]={level=CHAMPION_POINTS_20,quality=ITEM_QUALITY_MAGIC},
    [41]={level=CHAMPION_POINTS_30,quality=ITEM_QUALITY_MAGIC},
    [42]={level=CHAMPION_POINTS_40,quality=ITEM_QUALITY_MAGIC},
    [43]={level=CHAMPION_POINTS_50,quality=ITEM_QUALITY_MAGIC},
    [44]={level=CHAMPION_POINTS_60,quality=ITEM_QUALITY_MAGIC},
    [45]={level=CHAMPION_POINTS_70,quality=ITEM_QUALITY_MAGIC},
    [46]={level=CHAMPION_POINTS_80,quality=ITEM_QUALITY_MAGIC},
    [47]={level=CHAMPION_POINTS_90,quality=ITEM_QUALITY_MAGIC},
    [48]={level=CHAMPION_POINTS_100,quality=ITEM_QUALITY_MAGIC},
    [49]={level=NO_CHAMPION_POINTS,quality=ITEM_QUALITY_ARCANE},
    [50]={level=NO_CHAMPION_POINTS,quality=ITEM_QUALITY_ARCANE},
    [51]={level=CHAMPION_POINTS_10,quality=ITEM_QUALITY_MAGIC},
    [52]={level=CHAMPION_POINTS_20,quality=ITEM_QUALITY_MAGIC},
    [53]={level=CHAMPION_POINTS_30,quality=ITEM_QUALITY_MAGIC},
    [54]={level=CHAMPION_POINTS_40,quality=ITEM_QUALITY_MAGIC},
    [55]={level=CHAMPION_POINTS_50,quality=ITEM_QUALITY_MAGIC},
    [56]={level=CHAMPION_POINTS_60,quality=ITEM_QUALITY_MAGIC},
    [57]={level=CHAMPION_POINTS_70,quality=ITEM_QUALITY_MAGIC},
    [58]={level=CHAMPION_POINTS_80,quality=ITEM_QUALITY_MAGIC},
    [59]={level=CHAMPION_POINTS_90,quality=ITEM_QUALITY_MAGIC},
    [60]={level=CHAMPION_POINTS_100,quality=ITEM_QUALITY_MAGIC},
    [61]={level=CHAMPION_POINTS_10,quality=ITEM_QUALITY_ARCANE},
    [62]={level=CHAMPION_POINTS_20,quality=ITEM_QUALITY_ARCANE},
    [63]={level=CHAMPION_POINTS_30,quality=ITEM_QUALITY_ARCANE},
    [64]={level=CHAMPION_POINTS_40,quality=ITEM_QUALITY_ARCANE},
    [65]={level=CHAMPION_POINTS_50,quality=ITEM_QUALITY_ARCANE},
    [66]={level=CHAMPION_POINTS_60,quality=ITEM_QUALITY_ARCANE},
    [67]={level=CHAMPION_POINTS_70,quality=ITEM_QUALITY_ARCANE},
    [68]={level=CHAMPION_POINTS_80,quality=ITEM_QUALITY_ARCANE},
    [69]={level=CHAMPION_POINTS_90,quality=ITEM_QUALITY_ARCANE},
    [70]={level=CHAMPION_POINTS_100,quality=ITEM_QUALITY_ARCANE},
    [71]={level=CHAMPION_POINTS_10,quality=ITEM_QUALITY_ARTIFACT},
    [72]={level=CHAMPION_POINTS_20,quality=ITEM_QUALITY_ARTIFACT},
    [73]={level=CHAMPION_POINTS_30,quality=ITEM_QUALITY_ARTIFACT},
    [74]={level=CHAMPION_POINTS_40,quality=ITEM_QUALITY_ARTIFACT},
    [75]={level=CHAMPION_POINTS_50,quality=ITEM_QUALITY_ARTIFACT},
    [76]={level=CHAMPION_POINTS_60,quality=ITEM_QUALITY_ARTIFACT},
    [77]={level=CHAMPION_POINTS_70,quality=ITEM_QUALITY_ARTIFACT},
    [78]={level=CHAMPION_POINTS_80,quality=ITEM_QUALITY_ARTIFACT},
    [79]={level=CHAMPION_POINTS_90,quality=ITEM_QUALITY_ARTIFACT},
    [80]={level=CHAMPION_POINTS_100,quality=ITEM_QUALITY_ARTIFACT},
    [81]={level=CHAMPION_POINTS_10,quality=ITEM_QUALITY_ARCANE},
    [82]={level=CHAMPION_POINTS_20,quality=ITEM_QUALITY_ARCANE},
    [83]={level=CHAMPION_POINTS_30,quality=ITEM_QUALITY_ARCANE},
    [84]={level=CHAMPION_POINTS_40,quality=ITEM_QUALITY_ARCANE},
    [85]={level=CHAMPION_POINTS_50,quality=ITEM_QUALITY_ARCANE},
    [86]={level=CHAMPION_POINTS_60,quality=ITEM_QUALITY_ARCANE},
    [87]={level=CHAMPION_POINTS_70,quality=ITEM_QUALITY_ARCANE},
    [88]={level=CHAMPION_POINTS_80,quality=ITEM_QUALITY_ARCANE},
    [89]={level=CHAMPION_POINTS_90,quality=ITEM_QUALITY_ARCANE},
    [90]={level=CHAMPION_POINTS_100,quality=ITEM_QUALITY_ARCANE},
    [91]={level=CHAMPION_POINTS_10,quality=ITEM_QUALITY_ARTIFACT},
    [92]={level=CHAMPION_POINTS_20,quality=ITEM_QUALITY_ARTIFACT},
    [93]={level=CHAMPION_POINTS_30,quality=ITEM_QUALITY_ARTIFACT},
    [94]={level=CHAMPION_POINTS_40,quality=ITEM_QUALITY_ARTIFACT},
    [95]={level=CHAMPION_POINTS_50,quality=ITEM_QUALITY_ARTIFACT},
    [96]={level=CHAMPION_POINTS_60,quality=ITEM_QUALITY_ARTIFACT},
    [97]={level=CHAMPION_POINTS_70,quality=ITEM_QUALITY_ARTIFACT},
    [98]={level=CHAMPION_POINTS_80,quality=ITEM_QUALITY_ARTIFACT},
    [99]={level=CHAMPION_POINTS_90,quality=ITEM_QUALITY_ARTIFACT},
    [100]={level=CHAMPION_POINTS_100,quality=ITEM_QUALITY_ARTIFACT},
    [101]={level=CHAMPION_POINTS_10,quality=ITEM_QUALITY_LEGENDARY},
    [102]={level=CHAMPION_POINTS_20,quality=ITEM_QUALITY_LEGENDARY},
    [103]={level=CHAMPION_POINTS_30,quality=ITEM_QUALITY_LEGENDARY},
    [104]={level=CHAMPION_POINTS_40,quality=ITEM_QUALITY_LEGENDARY},
    [105]={level=CHAMPION_POINTS_50,quality=ITEM_QUALITY_LEGENDARY},
    [106]={level=CHAMPION_POINTS_60,quality=ITEM_QUALITY_LEGENDARY},
    [107]={level=CHAMPION_POINTS_70,quality=ITEM_QUALITY_LEGENDARY},
    [108]={level=CHAMPION_POINTS_80,quality=ITEM_QUALITY_LEGENDARY},
    [109]={level=CHAMPION_POINTS_90,quality=ITEM_QUALITY_LEGENDARY},
    [110]={level=CHAMPION_POINTS_100,quality=ITEM_QUALITY_LEGENDARY},
    [111]={level=CHAMPION_POINTS_10,quality=ITEM_QUALITY_NORMAL},
    [112]={level=CHAMPION_POINTS_20,quality=ITEM_QUALITY_NORMAL},
    [113]={level=CHAMPION_POINTS_30,quality=ITEM_QUALITY_NORMAL},
    [114]={level=CHAMPION_POINTS_40,quality=ITEM_QUALITY_NORMAL},
    [115]={level=CHAMPION_POINTS_50,quality=ITEM_QUALITY_NORMAL},
    [116]={level=CHAMPION_POINTS_60,quality=ITEM_QUALITY_NORMAL},
    [117]={level=CHAMPION_POINTS_70,quality=ITEM_QUALITY_NORMAL},
    [118]={level=CHAMPION_POINTS_80,quality=ITEM_QUALITY_NORMAL},
    [119]={level=CHAMPION_POINTS_90,quality=ITEM_QUALITY_NORMAL},
    [120]={level=CHAMPION_POINTS_100,quality=ITEM_QUALITY_NORMAL},
    [121]={level=NO_CHAMPION_POINTS,quality=ITEM_QUALITY_MAGIC},
    [122]={level=NO_CHAMPION_POINTS,quality=ITEM_QUALITY_ARCANE},
    [123]={level=NO_CHAMPION_POINTS,quality=ITEM_QUALITY_ARTIFACT},
    [124]={level=NO_CHAMPION_POINTS,quality=ITEM_QUALITY_LEGENDARY},
    [125]={level=CHAMPION_POINTS_10,quality=ITEM_QUALITY_NORMAL},
    [126]={level=CHAMPION_POINTS_20,quality=ITEM_QUALITY_NORMAL},
    [127]={level=CHAMPION_POINTS_30,quality=ITEM_QUALITY_NORMAL},
    [128]={level=CHAMPION_POINTS_40,quality=ITEM_QUALITY_NORMAL},
    [129]={level=CHAMPION_POINTS_50,quality=ITEM_QUALITY_NORMAL},
    [130]={level=CHAMPION_POINTS_60,quality=ITEM_QUALITY_NORMAL},
    [131]={level=CHAMPION_POINTS_70,quality=ITEM_QUALITY_NORMAL},
    [132]={level=CHAMPION_POINTS_80,quality=ITEM_QUALITY_NORMAL},
    [133]={level=CHAMPION_POINTS_90,quality=ITEM_QUALITY_NORMAL},
    [134]={level=CHAMPION_POINTS_100,quality=ITEM_QUALITY_NORMAL},
    [135]={level=CHAMPION_POINTS_10,quality=ITEM_QUALITY_MAGIC},
    [136]={level=CHAMPION_POINTS_20,quality=ITEM_QUALITY_MAGIC},
    [137]={level=CHAMPION_POINTS_30,quality=ITEM_QUALITY_MAGIC},
    [138]={level=CHAMPION_POINTS_40,quality=ITEM_QUALITY_MAGIC},
    [139]={level=CHAMPION_POINTS_50,quality=ITEM_QUALITY_MAGIC},
    [140]={level=CHAMPION_POINTS_60,quality=ITEM_QUALITY_MAGIC},
    [141]={level=CHAMPION_POINTS_70,quality=ITEM_QUALITY_MAGIC},
    [142]={level=CHAMPION_POINTS_80,quality=ITEM_QUALITY_MAGIC},
    [143]={level=CHAMPION_POINTS_90,quality=ITEM_QUALITY_MAGIC},
    [144]={level=CHAMPION_POINTS_100,quality=ITEM_QUALITY_MAGIC},
    [145]={level=CHAMPION_POINTS_10,quality=ITEM_QUALITY_ARCANE},
    [146]={level=CHAMPION_POINTS_20,quality=ITEM_QUALITY_ARCANE},
    [147]={level=CHAMPION_POINTS_30,quality=ITEM_QUALITY_ARCANE},
    [148]={level=CHAMPION_POINTS_40,quality=ITEM_QUALITY_ARCANE},
    [149]={level=CHAMPION_POINTS_50,quality=ITEM_QUALITY_ARCANE},
    [150]={level=CHAMPION_POINTS_60,quality=ITEM_QUALITY_ARCANE},
    [151]={level=CHAMPION_POINTS_70,quality=ITEM_QUALITY_ARCANE},
    [152]={level=CHAMPION_POINTS_80,quality=ITEM_QUALITY_ARCANE},
    [153]={level=CHAMPION_POINTS_90,quality=ITEM_QUALITY_ARCANE},
    [154]={level=CHAMPION_POINTS_100,quality=ITEM_QUALITY_ARCANE},
    [155]={level=CHAMPION_POINTS_10,quality=ITEM_QUALITY_ARTIFACT},
    [156]={level=CHAMPION_POINTS_20,quality=ITEM_QUALITY_ARTIFACT},
    [157]={level=CHAMPION_POINTS_30,quality=ITEM_QUALITY_ARTIFACT},
    [158]={level=CHAMPION_POINTS_40,quality=ITEM_QUALITY_ARTIFACT},
    [159]={level=CHAMPION_POINTS_50,quality=ITEM_QUALITY_ARTIFACT},
    [160]={level=CHAMPION_POINTS_60,quality=ITEM_QUALITY_ARTIFACT},
    [161]={level=CHAMPION_POINTS_70,quality=ITEM_QUALITY_ARTIFACT},
    [162]={level=CHAMPION_POINTS_80,quality=ITEM_QUALITY_ARTIFACT},
    [163]={level=CHAMPION_POINTS_90,quality=ITEM_QUALITY_ARTIFACT},
    [164]={level=CHAMPION_POINTS_100,quality=ITEM_QUALITY_ARTIFACT},
    [165]={level=CHAMPION_POINTS_10,quality=ITEM_QUALITY_LEGENDARY},
    [166]={level=CHAMPION_POINTS_20,quality=ITEM_QUALITY_LEGENDARY},
    [167]={level=CHAMPION_POINTS_30,quality=ITEM_QUALITY_LEGENDARY},
    [168]={level=CHAMPION_POINTS_40,quality=ITEM_QUALITY_LEGENDARY},
    [169]={level=CHAMPION_POINTS_50,quality=ITEM_QUALITY_LEGENDARY},
    [170]={level=CHAMPION_POINTS_60,quality=ITEM_QUALITY_LEGENDARY},
    [171]={level=CHAMPION_POINTS_70,quality=ITEM_QUALITY_LEGENDARY},
    [172]={level=CHAMPION_POINTS_80,quality=ITEM_QUALITY_LEGENDARY},
    [173]={level=CHAMPION_POINTS_90,quality=ITEM_QUALITY_LEGENDARY},
    [174]={level=CHAMPION_POINTS_100,quality=ITEM_QUALITY_LEGENDARY},
    [175]={level=NO_CHAMPION_POINTS,quality=ITEM_QUALITY_NORMAL},
    [176]={level=NO_CHAMPION_POINTS,quality=ITEM_QUALITY_NORMAL},
    [177]={level=NO_CHAMPION_POINTS,quality=ITEM_QUALITY_TRASH},
    [178]={level=CHAMPION_POINTS_10,quality=ITEM_QUALITY_NORMAL},
    [179]={level=CHAMPION_POINTS_20,quality=ITEM_QUALITY_NORMAL},
    [180]={level=CHAMPION_POINTS_30,quality=ITEM_QUALITY_NORMAL},
    [181]={level=CHAMPION_POINTS_40,quality=ITEM_QUALITY_NORMAL},
    [182]={level=CHAMPION_POINTS_50,quality=ITEM_QUALITY_NORMAL},
    [183]={level=CHAMPION_POINTS_60,quality=ITEM_QUALITY_NORMAL},
    [184]={level=CHAMPION_POINTS_70,quality=ITEM_QUALITY_NORMAL},
    [185]={level=CHAMPION_POINTS_80,quality=ITEM_QUALITY_NORMAL},
    [186]={level=CHAMPION_POINTS_90,quality=ITEM_QUALITY_NORMAL},
    [187]={level=CHAMPION_POINTS_100,quality=ITEM_QUALITY_NORMAL},
    [188]={level=CHAMPION_POINTS_10,quality=ITEM_QUALITY_MAGIC},
    [189]={level=CHAMPION_POINTS_20,quality=ITEM_QUALITY_MAGIC},
    [190]={level=CHAMPION_POINTS_30,quality=ITEM_QUALITY_MAGIC},
    [191]={level=CHAMPION_POINTS_40,quality=ITEM_QUALITY_MAGIC},
    [192]={level=CHAMPION_POINTS_50,quality=ITEM_QUALITY_MAGIC},
    [193]={level=CHAMPION_POINTS_60,quality=ITEM_QUALITY_MAGIC},
    [194]={level=CHAMPION_POINTS_70,quality=ITEM_QUALITY_MAGIC},
    [195]={level=CHAMPION_POINTS_80,quality=ITEM_QUALITY_MAGIC},
    [196]={level=CHAMPION_POINTS_90,quality=ITEM_QUALITY_MAGIC},
    [197]={level=CHAMPION_POINTS_100,quality=ITEM_QUALITY_MAGIC},
    [198]={level=CHAMPION_POINTS_10,quality=ITEM_QUALITY_ARCANE},
    [199]={level=CHAMPION_POINTS_20,quality=ITEM_QUALITY_ARCANE},
    [200]={level=CHAMPION_POINTS_30,quality=ITEM_QUALITY_ARCANE},
    [201]={level=CHAMPION_POINTS_40,quality=ITEM_QUALITY_ARCANE},
    [202]={level=CHAMPION_POINTS_50,quality=ITEM_QUALITY_ARCANE},
    [203]={level=CHAMPION_POINTS_60,quality=ITEM_QUALITY_ARCANE},
    [204]={level=CHAMPION_POINTS_70,quality=ITEM_QUALITY_ARCANE},
    [205]={level=CHAMPION_POINTS_80,quality=ITEM_QUALITY_ARCANE},
    [206]={level=CHAMPION_POINTS_90,quality=ITEM_QUALITY_ARCANE},
    [207]={level=CHAMPION_POINTS_100,quality=ITEM_QUALITY_ARCANE},
    [208]={level=CHAMPION_POINTS_10,quality=ITEM_QUALITY_ARTIFACT},
    [209]={level=CHAMPION_POINTS_20,quality=ITEM_QUALITY_ARTIFACT},
    [210]={level=CHAMPION_POINTS_30,quality=ITEM_QUALITY_ARTIFACT},
    [211]={level=CHAMPION_POINTS_40,quality=ITEM_QUALITY_ARTIFACT},
    [212]={level=CHAMPION_POINTS_50,quality=ITEM_QUALITY_ARTIFACT},
    [213]={level=CHAMPION_POINTS_60,quality=ITEM_QUALITY_ARTIFACT},
    [214]={level=CHAMPION_POINTS_70,quality=ITEM_QUALITY_ARTIFACT},
    [215]={level=CHAMPION_POINTS_80,quality=ITEM_QUALITY_ARTIFACT},
    [216]={level=CHAMPION_POINTS_90,quality=ITEM_QUALITY_ARTIFACT},
    [217]={level=CHAMPION_POINTS_100,quality=ITEM_QUALITY_ARTIFACT},
    [218]={level=CHAMPION_POINTS_10,quality=ITEM_QUALITY_LEGENDARY},
    [219]={level=CHAMPION_POINTS_20,quality=ITEM_QUALITY_LEGENDARY},
    [220]={level=CHAMPION_POINTS_30,quality=ITEM_QUALITY_LEGENDARY},
    [221]={level=CHAMPION_POINTS_40,quality=ITEM_QUALITY_LEGENDARY},
    [222]={level=CHAMPION_POINTS_50,quality=ITEM_QUALITY_LEGENDARY},
    [223]={level=CHAMPION_POINTS_60,quality=ITEM_QUALITY_LEGENDARY},
    [224]={level=CHAMPION_POINTS_70,quality=ITEM_QUALITY_LEGENDARY},
    [225]={level=CHAMPION_POINTS_80,quality=ITEM_QUALITY_LEGENDARY},
    [226]={level=CHAMPION_POINTS_90,quality=ITEM_QUALITY_LEGENDARY},
    [227]={level=CHAMPION_POINTS_100,quality=ITEM_QUALITY_LEGENDARY},
    [228]={level=CHAMPION_POINTS_110,quality=ITEM_QUALITY_MAGIC},
    [229]={level=CHAMPION_POINTS_110,quality=ITEM_QUALITY_MAGIC},
    [230]={level=CHAMPION_POINTS_110,quality=ITEM_QUALITY_ARCANE},
    [231]={level=CHAMPION_POINTS_110,quality=ITEM_QUALITY_ARTIFACT},
    [232]={level=CHAMPION_POINTS_110,quality=ITEM_QUALITY_ARCANE},
    [233]={level=CHAMPION_POINTS_110,quality=ITEM_QUALITY_ARTIFACT},
    [234]={level=CHAMPION_POINTS_110,quality=ITEM_QUALITY_LEGENDARY},
    [235]={level=CHAMPION_POINTS_110,quality=ITEM_QUALITY_NORMAL},
    [236]={level=CHAMPION_POINTS_110,quality=ITEM_QUALITY_NORMAL},
    [237]={level=CHAMPION_POINTS_110,quality=ITEM_QUALITY_MAGIC},
    [238]={level=CHAMPION_POINTS_110,quality=ITEM_QUALITY_ARCANE},
    [239]={level=CHAMPION_POINTS_110,quality=ITEM_QUALITY_ARTIFACT},
    [240]={level=CHAMPION_POINTS_110,quality=ITEM_QUALITY_LEGENDARY},
    [241]={level=CHAMPION_POINTS_110,quality=ITEM_QUALITY_NORMAL},
    [242]={level=CHAMPION_POINTS_110,quality=ITEM_QUALITY_MAGIC},
    [243]={level=CHAMPION_POINTS_110,quality=ITEM_QUALITY_ARCANE},
    [244]={level=CHAMPION_POINTS_110,quality=ITEM_QUALITY_ARTIFACT},
    [245]={level=CHAMPION_POINTS_110,quality=ITEM_QUALITY_LEGENDARY},
    [246]={level=CHAMPION_POINTS_120,quality=ITEM_QUALITY_MAGIC},
    [247]={level=CHAMPION_POINTS_120,quality=ITEM_QUALITY_MAGIC},
    [248]={level=CHAMPION_POINTS_120,quality=ITEM_QUALITY_ARCANE},
    [249]={level=CHAMPION_POINTS_120,quality=ITEM_QUALITY_ARTIFACT},
    [250]={level=CHAMPION_POINTS_120,quality=ITEM_QUALITY_ARCANE},
    [251]={level=CHAMPION_POINTS_120,quality=ITEM_QUALITY_ARTIFACT},
    [252]={level=CHAMPION_POINTS_120,quality=ITEM_QUALITY_LEGENDARY},
    [253]={level=CHAMPION_POINTS_120,quality=ITEM_QUALITY_NORMAL},
    [254]={level=CHAMPION_POINTS_120,quality=ITEM_QUALITY_NORMAL},
    [255]={level=CHAMPION_POINTS_120,quality=ITEM_QUALITY_MAGIC},
    [256]={level=CHAMPION_POINTS_120,quality=ITEM_QUALITY_ARCANE},
    [257]={level=CHAMPION_POINTS_120,quality=ITEM_QUALITY_ARTIFACT},
    [258]={level=CHAMPION_POINTS_120,quality=ITEM_QUALITY_LEGENDARY},
    [259]={level=CHAMPION_POINTS_120,quality=ITEM_QUALITY_NORMAL},
    [260]={level=CHAMPION_POINTS_120,quality=ITEM_QUALITY_MAGIC},
    [261]={level=CHAMPION_POINTS_120,quality=ITEM_QUALITY_ARCANE},
    [262]={level=CHAMPION_POINTS_120,quality=ITEM_QUALITY_ARTIFACT},
    [263]={level=CHAMPION_POINTS_120,quality=ITEM_QUALITY_LEGENDARY},
    [264]={level=CHAMPION_POINTS_130,quality=ITEM_QUALITY_MAGIC},
    [265]={level=CHAMPION_POINTS_130,quality=ITEM_QUALITY_MAGIC},
    [266]={level=CHAMPION_POINTS_130,quality=ITEM_QUALITY_ARCANE},
    [267]={level=CHAMPION_POINTS_130,quality=ITEM_QUALITY_ARTIFACT},
    [268]={level=CHAMPION_POINTS_130,quality=ITEM_QUALITY_ARCANE},
    [269]={level=CHAMPION_POINTS_130,quality=ITEM_QUALITY_ARTIFACT},
    [270]={level=CHAMPION_POINTS_130,quality=ITEM_QUALITY_LEGENDARY},
    [271]={level=CHAMPION_POINTS_130,quality=ITEM_QUALITY_NORMAL},
    [272]={level=CHAMPION_POINTS_130,quality=ITEM_QUALITY_NORMAL},
    [273]={level=CHAMPION_POINTS_130,quality=ITEM_QUALITY_MAGIC},
    [274]={level=CHAMPION_POINTS_130,quality=ITEM_QUALITY_ARCANE},
    [275]={level=CHAMPION_POINTS_130,quality=ITEM_QUALITY_ARTIFACT},
    [276]={level=CHAMPION_POINTS_130,quality=ITEM_QUALITY_LEGENDARY},
    [277]={level=CHAMPION_POINTS_130,quality=ITEM_QUALITY_NORMAL},
    [278]={level=CHAMPION_POINTS_130,quality=ITEM_QUALITY_MAGIC},
    [279]={level=CHAMPION_POINTS_130,quality=ITEM_QUALITY_ARCANE},
    [280]={level=CHAMPION_POINTS_130,quality=ITEM_QUALITY_ARTIFACT},
    [281]={level=CHAMPION_POINTS_130,quality=ITEM_QUALITY_LEGENDARY},
    [282]={level=CHAMPION_POINTS_140,quality=ITEM_QUALITY_MAGIC},
    [283]={level=CHAMPION_POINTS_140,quality=ITEM_QUALITY_MAGIC},
    [284]={level=CHAMPION_POINTS_140,quality=ITEM_QUALITY_ARCANE},
    [285]={level=CHAMPION_POINTS_140,quality=ITEM_QUALITY_ARTIFACT},
    [286]={level=CHAMPION_POINTS_140,quality=ITEM_QUALITY_ARCANE},
    [287]={level=CHAMPION_POINTS_140,quality=ITEM_QUALITY_ARTIFACT},
    [288]={level=CHAMPION_POINTS_140,quality=ITEM_QUALITY_LEGENDARY},
    [289]={level=CHAMPION_POINTS_140,quality=ITEM_QUALITY_NORMAL},
    [290]={level=CHAMPION_POINTS_140,quality=ITEM_QUALITY_NORMAL},
    [291]={level=CHAMPION_POINTS_140,quality=ITEM_QUALITY_MAGIC},
    [292]={level=CHAMPION_POINTS_140,quality=ITEM_QUALITY_ARCANE},
    [293]={level=CHAMPION_POINTS_140,quality=ITEM_QUALITY_ARTIFACT},
    [294]={level=CHAMPION_POINTS_140,quality=ITEM_QUALITY_LEGENDARY},
    [295]={level=CHAMPION_POINTS_140,quality=ITEM_QUALITY_NORMAL},
    [296]={level=CHAMPION_POINTS_140,quality=ITEM_QUALITY_MAGIC},
    [297]={level=CHAMPION_POINTS_140,quality=ITEM_QUALITY_ARCANE},
    [298]={level=CHAMPION_POINTS_140,quality=ITEM_QUALITY_ARTIFACT},
    [299]={level=CHAMPION_POINTS_140,quality=ITEM_QUALITY_LEGENDARY},
    [300]={level=CHAMPION_POINTS_150,quality=ITEM_QUALITY_MAGIC},
    [301]={level=CHAMPION_POINTS_150,quality=ITEM_QUALITY_MAGIC},
    [302]={level=CHAMPION_POINTS_150,quality=ITEM_QUALITY_ARCANE},
    [303]={level=CHAMPION_POINTS_150,quality=ITEM_QUALITY_ARTIFACT},
    [304]={level=CHAMPION_POINTS_150,quality=ITEM_QUALITY_ARCANE},
    [305]={level=CHAMPION_POINTS_150,quality=ITEM_QUALITY_ARTIFACT},
    [306]={level=CHAMPION_POINTS_150,quality=ITEM_QUALITY_LEGENDARY},
    [307]={level=CHAMPION_POINTS_150,quality=ITEM_QUALITY_NORMAL},
    [308]={level=CHAMPION_POINTS_150,quality=ITEM_QUALITY_NORMAL},
    [309]={level=CHAMPION_POINTS_150,quality=ITEM_QUALITY_MAGIC},
    [310]={level=CHAMPION_POINTS_150,quality=ITEM_QUALITY_ARCANE},
    [311]={level=CHAMPION_POINTS_150,quality=ITEM_QUALITY_ARTIFACT},
    [312]={level=CHAMPION_POINTS_150,quality=ITEM_QUALITY_LEGENDARY},
    [313]={level=CHAMPION_POINTS_150,quality=ITEM_QUALITY_NORMAL},
    [314]={level=CHAMPION_POINTS_150,quality=ITEM_QUALITY_MAGIC},
    [315]={level=CHAMPION_POINTS_150,quality=ITEM_QUALITY_ARCANE},
    [316]={level=CHAMPION_POINTS_150,quality=ITEM_QUALITY_ARTIFACT},
    [317]={level=CHAMPION_POINTS_150,quality=ITEM_QUALITY_LEGENDARY},
    [318]={level=NO_CHAMPION_POINTS,quality=ITEM_QUALITY_TRASH},
    [319]={level=NO_CHAMPION_POINTS,quality=ITEM_QUALITY_NORMAL},
    [320]={level=NO_CHAMPION_POINTS,quality=ITEM_QUALITY_MAGIC},
    [321]={level=NO_CHAMPION_POINTS,quality=ITEM_QUALITY_ARCANE},
    [322]={level=NO_CHAMPION_POINTS,quality=ITEM_QUALITY_ARTIFACT},
    [323]={level=NO_CHAMPION_POINTS,quality=ITEM_QUALITY_LEGENDARY},
    [324]={level=CHAMPION_POINTS_10,quality=ITEM_QUALITY_NORMAL},
    [325]={level=CHAMPION_POINTS_20,quality=ITEM_QUALITY_NORMAL},
    [326]={level=CHAMPION_POINTS_30,quality=ITEM_QUALITY_NORMAL},
    [327]={level=CHAMPION_POINTS_40,quality=ITEM_QUALITY_NORMAL},
    [328]={level=CHAMPION_POINTS_50,quality=ITEM_QUALITY_NORMAL},
    [329]={level=CHAMPION_POINTS_60,quality=ITEM_QUALITY_NORMAL},
    [330]={level=CHAMPION_POINTS_70,quality=ITEM_QUALITY_NORMAL},
    [331]={level=CHAMPION_POINTS_80,quality=ITEM_QUALITY_NORMAL},
    [332]={level=CHAMPION_POINTS_90,quality=ITEM_QUALITY_NORMAL},
    [333]={level=CHAMPION_POINTS_100,quality=ITEM_QUALITY_NORMAL},
    [334]={level=CHAMPION_POINTS_110,quality=ITEM_QUALITY_NORMAL},
    [335]={level=CHAMPION_POINTS_120,quality=ITEM_QUALITY_NORMAL},
    [336]={level=CHAMPION_POINTS_130,quality=ITEM_QUALITY_NORMAL},
    [337]={level=CHAMPION_POINTS_140,quality=ITEM_QUALITY_NORMAL},
    [338]={level=CHAMPION_POINTS_150,quality=ITEM_QUALITY_NORMAL},
    [339]={level=CHAMPION_POINTS_10,quality=ITEM_QUALITY_MAGIC},
    [340]={level=CHAMPION_POINTS_20,quality=ITEM_QUALITY_MAGIC},
    [341]={level=CHAMPION_POINTS_30,quality=ITEM_QUALITY_MAGIC},
    [342]={level=CHAMPION_POINTS_40,quality=ITEM_QUALITY_MAGIC},
    [343]={level=CHAMPION_POINTS_50,quality=ITEM_QUALITY_MAGIC},
    [344]={level=CHAMPION_POINTS_60,quality=ITEM_QUALITY_MAGIC},
    [345]={level=CHAMPION_POINTS_70,quality=ITEM_QUALITY_MAGIC},
    [346]={level=CHAMPION_POINTS_80,quality=ITEM_QUALITY_MAGIC},
    [347]={level=CHAMPION_POINTS_90,quality=ITEM_QUALITY_MAGIC},
    [348]={level=CHAMPION_POINTS_100,quality=ITEM_QUALITY_MAGIC},
    [349]={level=CHAMPION_POINTS_110,quality=ITEM_QUALITY_MAGIC},
    [350]={level=CHAMPION_POINTS_120,quality=ITEM_QUALITY_MAGIC},
    [351]={level=CHAMPION_POINTS_130,quality=ITEM_QUALITY_MAGIC},
    [352]={level=CHAMPION_POINTS_140,quality=ITEM_QUALITY_MAGIC},
    [353]={level=CHAMPION_POINTS_150,quality=ITEM_QUALITY_MAGIC},
    [354]={level=CHAMPION_POINTS_120,quality=ITEM_QUALITY_ARTIFACT},
    [355]={level=CHAMPION_POINTS_120,quality=ITEM_QUALITY_LEGENDARY},
    [356]={level=NO_CHAMPION_POINTS,quality=ITEM_QUALITY_NORMAL},
    [357]={level=NO_CHAMPION_POINTS,quality=ITEM_QUALITY_NORMAL},
    [358]={level=CHAMPION_POINTS_160,quality=ITEM_QUALITY_MAGIC},
    [359]={level=CHAMPION_POINTS_160,quality=ITEM_QUALITY_MAGIC},
    [360]={level=CHAMPION_POINTS_160,quality=ITEM_QUALITY_ARCANE},
    [361]={level=CHAMPION_POINTS_160,quality=ITEM_QUALITY_ARTIFACT},
    [362]={level=CHAMPION_POINTS_160,quality=ITEM_QUALITY_ARCANE},
    [363]={level=CHAMPION_POINTS_160,quality=ITEM_QUALITY_ARTIFACT},
    [364]={level=CHAMPION_POINTS_160,quality=ITEM_QUALITY_LEGENDARY},
    [365]={level=CHAMPION_POINTS_160,quality=ITEM_QUALITY_NORMAL},
    [366]={level=CHAMPION_POINTS_160,quality=ITEM_QUALITY_NORMAL},
    [367]={level=CHAMPION_POINTS_160,quality=ITEM_QUALITY_MAGIC},
    [368]={level=CHAMPION_POINTS_160,quality=ITEM_QUALITY_ARCANE},
    [369]={level=CHAMPION_POINTS_160,quality=ITEM_QUALITY_ARTIFACT},
    [370]={level=CHAMPION_POINTS_160,quality=ITEM_QUALITY_LEGENDARY},
    [371]={level=CHAMPION_POINTS_160,quality=ITEM_QUALITY_NORMAL},
    [372]={level=CHAMPION_POINTS_160,quality=ITEM_QUALITY_MAGIC},
    [373]={level=CHAMPION_POINTS_160,quality=ITEM_QUALITY_ARCANE},
    [374]={level=CHAMPION_POINTS_160,quality=ITEM_QUALITY_ARTIFACT},
    [375]={level=CHAMPION_POINTS_160,quality=ITEM_QUALITY_LEGENDARY},
    [376]={level=CHAMPION_POINTS_160,quality=ITEM_QUALITY_NORMAL},
    [377]={level=CHAMPION_POINTS_160,quality=ITEM_QUALITY_MAGIC},
    [378]={level=NO_CHAMPION_POINTS,quality=ITEM_QUALITY_NORMAL},
    [379]={level=NO_CHAMPION_POINTS,quality=ITEM_QUALITY_NORMAL},
    [380]={level=CHAMPION_POINTS_170,quality=ITEM_QUALITY_MAGIC},
    [381]={level=CHAMPION_POINTS_170,quality=ITEM_QUALITY_MAGIC},
    [382]={level=CHAMPION_POINTS_170,quality=ITEM_QUALITY_ARCANE},
    [383]={level=CHAMPION_POINTS_170,quality=ITEM_QUALITY_ARTIFACT},
    [384]={level=CHAMPION_POINTS_170,quality=ITEM_QUALITY_ARCANE},
    [385]={level=CHAMPION_POINTS_170,quality=ITEM_QUALITY_ARTIFACT},
    [386]={level=CHAMPION_POINTS_170,quality=ITEM_QUALITY_LEGENDARY},
    [387]={level=CHAMPION_POINTS_170,quality=ITEM_QUALITY_NORMAL},
    [388]={level=CHAMPION_POINTS_170,quality=ITEM_QUALITY_NORMAL},
    [389]={level=CHAMPION_POINTS_170,quality=ITEM_QUALITY_MAGIC},
    [390]={level=CHAMPION_POINTS_170,quality=ITEM_QUALITY_ARCANE},
    [391]={level=CHAMPION_POINTS_170,quality=ITEM_QUALITY_ARTIFACT},
    [392]={level=CHAMPION_POINTS_170,quality=ITEM_QUALITY_LEGENDARY},
    [393]={level=CHAMPION_POINTS_170,quality=ITEM_QUALITY_NORMAL},
    [394]={level=CHAMPION_POINTS_170,quality=ITEM_QUALITY_MAGIC},
    [395]={level=CHAMPION_POINTS_170,quality=ITEM_QUALITY_ARCANE},
    [396]={level=CHAMPION_POINTS_170,quality=ITEM_QUALITY_ARTIFACT},
    [397]={level=CHAMPION_POINTS_170,quality=ITEM_QUALITY_LEGENDARY},
    [398]={level=CHAMPION_POINTS_170,quality=ITEM_QUALITY_NORMAL},
    [399]={level=CHAMPION_POINTS_170,quality=ITEM_QUALITY_MAGIC},
    [400]={level=CHAMPION_POINTS_180,quality=ITEM_QUALITY_MAGIC},
}
]]
------------------------------------------------------------------------------------------------------------------------